name: 'Build-Testing'

on:  
  pull_request:
    branches: [ master]

jobs:
  build-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: yarn
      
      - name: check build
      - run: 

      # Add more steps for building and testing here
