name: 'publish'


on:  
  push:
    branches: [ master ]



jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install
          yarn build
          yarn set version 4.0.2
      - name: version up
        run: |
          yarn version-patch
      - name: change package.json push
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add package.json
          git commit -m 'publish packages with npm'
          git push origin master
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

          
        
